# vim: autoindent:expandtab:sw=2:ts=2
---
- name: Setup Minecraft Client
  hosts: localhost
  become: no
  tasks:
  - name: Variables
    include_vars:
      file: vars/minecraft.yml
      name: minecraft
  - name: Install Mods
    get_url:
      dest: "{{ minecraft.client.directory }}/mods/{{ item.filename }}"
      url: "{{ item.url }}"
    with_items: "{{ minecraft.forge.mods }}"
    when:
      - minecraft.server.type == "forge"
  - name: Create info.html
    template:
      src: templates/info.html.j2
      dest: /tmp/info.html
      mode: 0644
    when:
      - minecraft.server.type == "forge"
  - name: Create info.md
    template:
      src: templates/info.md.j2
      dest: /tmp/info.md
      mode: 0644
    when:
      - minecraft.server.type == "forge"

